# Source: php-helloworld/templates/sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: php-helloworld-php-helloworld
  annotations:
    meta.helm.sh/release-name: 'php-helloworld'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
