# Source: jxboot-helmfile-resources/templates/build-bot-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "tekton-bot"
  annotations:
    iam.gke.io/gcp-service-account: tf-jx-prime-tuna-tekton@serious-truck-345118.iam.gserviceaccount.com
    meta.helm.sh/release-name: 'jxboot-helmfile-resources'
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
secrets:
  - name: tekton-container-registry-auth
  - name: tekton-git
